### ISSUE TITLE
Veskitammi tn - Laagri Selveri vaheline kergtee

### ISSUE THREAD

**Issue by tormi** [sauevald/laagri#3]
## Probleem

Veskitammi tänava ja ehitatava Laagri Selveri vahel puudub kergtee. See on küll projekteeritud, kuid jääb (rahapuudusel?) välja ehitamata tekitades seeläbi liiklusohtliku olukorra. Projekteeritud kergtee osa Selverist Pääsküla jõeni on ehitamisel ja meelitab kergliiklejad kuni jõeni, kust edasi Veskitammi tänava ääres kulgevale kergteele pääseb ainult Pärnu mnt äärt mööda. 

Skeemil rohelisega on kavandatud ja ehitatavad kergteed, punasega algselt kavandatud, kuid ära jäetav kergtee lõik.

![selver - veskitammi klt](https://user-images.githubusercontent.com/146800/29238434-3c330ada-7f3e-11e7-9c99-5ad395f03e9c.png)
![20170811_122243](https://user-images.githubusercontent.com/146800/29238459-b304d602-7f3e-11e7-9400-ec6be5013314.jpg)
![20170811_122324](https://user-images.githubusercontent.com/146800/29238463-c7c85492-7f3e-11e7-82ea-9515ca91cb16.jpg)
_Pildid Tormi Tabor, 11.08.2017_

Värskes [Nõmme linnaosa üldplaneeringus](http://www.tallinn.ee/est/ehitus/Nomme-linnaosa-uldplaneering) on ära jäetav lõik märgitud perspektiivse kergliiklustee magistraalina.

![nomme-up](https://user-images.githubusercontent.com/146800/29238525-1be6f8d4-7f40-11e7-8116-f21b0cbbdcf3.jpg)

### Materjalid
- [Riigihange 185849: Riigitee 4 Tallinn-Pärnu-Ikla km 13,0-13,7 Veskitammi liiklussõlme ehitus](https://riigihanked.riik.ee/register/hange/185849)
- minu artikkel, milles teen ettepaneku projektlahendust muuta: https://medium.com/saue/magistraal-topist-vana-p%C3%A4%C3%A4sk%C3%BClla-c24955a0eda9
- Maanteeameti eitav vastus: https://medium.com/@tormi/maanteeametist-tuli-vastus-ettepanekule-kahjuks-tulemusteta-6a2a23f529b2

**Comment by wipsise** [comment]
Tundub, et seda hanketähtaega on vahepeal pikendatud, st ehitus käesoleval aastal ei lõppe, tõenäoliselt saab olema talv läbi keeruline. Seega oleks võimalik aeg maha võtta ja projekt korda teha, talvel uuesti hankesse panna, kevadel ja suvel tööd korrektselt teha.

**Comment by tormi** [comment]
Vald on vähemalt maateemadega indikeerinud, et sinna võiks kergtee tulla - Uuekõrtsi kinnistust on volikogu otsusega omandatud maasiil kergtee rajamiseks:
- [Seljaku tn 2 kinnistu ja Uuekõrtsi kinnistust äralõike tasu eest omandamine](https://server.amphora.ee/atp/sauevald/index.aspx?type=12&id=300032)

![screenshot from 2017-08-15 02-51-00](https://user-images.githubusercontent.com/146800/29296696-9f5306d8-8164-11e7-9638-86eab2d25fa4.png)
![screenshot from 2017-08-15 02-49-00](https://user-images.githubusercontent.com/146800/29296659-5d646014-8164-11e7-90c5-ba62588d2807.png)
![screenshot from 2017-08-15 02-38-57](https://user-images.githubusercontent.com/146800/29296431-f027d0a4-8162-11e7-9a96-aead41414424.png)

**Comment by tormi** [comment]
### Riigimaantee nr 4 Tallinn – Pärnu – Ikla lõigu Vana-Pääsküla – Topi km 13,0-16,4 tehnilise projekti liiklusohutuse auditeerimine

- Põhimaantee nr 4 Vana-Pääsküla – Topi lõigu km 13,0-16,4 tehnilise projekti liiklusohutuse audit: [Pääsküla-Topi TP LOA aruanne.docx](https://github.com/sauevald/laagri/files/1223840/Paaskula-Topi.TP.LOA.aruanne.docx)
- Pädeva asutuse otsused liiklusohutusauditi koosseisus esitatud ettepanekute osas:
 [LOA_otsuse_protokoll.docx](https://github.com/sauevald/laagri/files/1223830/LOA_otsuse_protokoll.docx)

![screenshot from 2017-08-15 03-48-52](https://user-images.githubusercontent.com/146800/29297926-fc7b7eaa-816c-11e7-8d0b-b2b00f27ee8b.png)


> 14. august 2017 10:04 kirjutas Rašid Pulatov <Rasid.Pulatov@mnt.ee>:
> 
>     Tere,
> 
>     Edastan Teile päringus toodud materjalid. Projektile on teostatud LOA, mis arvestab täna ehitushankesse mineva lahendusega. Lisaks on manuses pädeva asutuse otsused.
> 
>     Tellija on arvestanud ka liiklusele avamise eelse auditi teostamisega.
> 
>     Parimat,
>     Rasid Pulatov
> 
>     From: Raul Vibo [mailto:raul.vibo@eesti.ee]
>     Sent: Sunday, August 13, 2017 9:34 AM
>     To: Rašid Pulatov <Rasid.Pulatov@mnt.ee>
>     Cc: Tormi Tabor <tormi.tabor@gmail.com>
>     Subject: Veskitammi ristmiku LOA
> 
>     Tere Rašid
> 
>     Viidates Tormi Tabori artiklile uurin, kas Veskitammi ristmiku projektile, mis käesoleval hetkel on ehitushankes, on läbiviidud ka liiklusohutuse audit? Kui on, palun jagada auditi aruannet ja pädeva asutuse otsused.
> 
>     Kas ehitushankes on arvestatud ka liiklusele avamise eelse auditiga?
> 
>     viide: https://medium.com/@tormi/maanteeametist-tuli-vastus-ettepanekule-kahjuks-tulemusteta-6a2a23f529b2
> 
>     Ette tänades,
> 
>     Raul Vibo
>     raul.vibo@eesti.ee
>     https://liiklusohutusaudit.ee

**Comment by tormi** [comment]
> 15. august 2017 03:30 kirjutas Tormi Tabor <tormi.tabor@gmail.com>:
> 
> Tere.
> 
> Tänud materjalide eest! Kas saan auditi pealkirjast ("Riigimaantee nr 4 Tallinn – Pärnu – Ikla lõigu Vana-Pääsküla – Topi **km 13,0**-16,4 tehnilise projekti liiklusohutuse auditeerimine") õieti aru, et auditeeritud lõik algas Tallinna piirilt (_km 13,0_) ja mitte Veskitammi tänavast? Sellisel juhul on enam kui arusaamatu, miks ei ole auditis sõnagagi kajastatud probleemi, millele oma artiklis viitasin: https://github.com/sauevald/laagri/issues/3
> 
> ![screenshot from 2017-08-15 11-45-26](https://user-images.githubusercontent.com/146800/29308657-4fa164f4-81af-11e7-8c6b-c551a87aab46.png)
> 
> Tervitades,
> Tormi Tabor
> 5451 3000

**Comment by tormi** [comment]
Lahendatud, lõik on töös.
